# Generated by Django 5.1.4 on 2025-02-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='detail_offer',
        ),
    ]
