# Generated by Django 5.1.4 on 2025-02-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_remove_order_detail_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custom_user',
            new_name='customer_user',
        ),
    ]
