# Generated by Django 5.1.4 on 2025-01-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttoken',
            name='key',
            field=models.CharField(default='et06iwexpUgIJAI18g7xX7oH9aIucklZA6pgiS7G', max_length=40, unique=True),
        ),
    ]
