# Generated by Django 5.1.4 on 2025-01-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_guesttoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttoken',
            name='key',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
