# Generated by Django 5.1.4 on 2025-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField()),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('business_profile_count', models.IntegerField()),
                ('offer_count', models.IntegerField()),
            ],
        ),
    ]
